# Generated by Django 3.2.4 on 2022-01-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211117_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(db_index=True, default='inactive', max_length=15, verbose_name='status'),
        ),
    ]
